import type { MapLayers, PanelConfig } from '@/types';

export const BOOKS_PANELS: Record<string, PanelConfig> = {
  map: { name: 'B5K Global Map', enabled: true, priority: 1 },
  'build-book': { name: 'Request A Book Build', enabled: true, priority: 1 },
  'public-domain-books': { name: 'Free Public Domain Books', enabled: true, priority: 1 },
  'live-news': { name: 'Literary News', enabled: true, priority: 1 },
  'live-webcams': { name: 'Literary Live Streams', enabled: true, priority: 2 },
  insights: { name: 'Literary Insights', enabled: true, priority: 1 },
  'publishing-news': { name: 'Publishing News', enabled: true, priority: 1 },
  'book-reviews': { name: 'Book Reviews', enabled: true, priority: 1 },
  'literary-awards': { name: 'Literary Awards', enabled: true, priority: 2 },
  'industry-analysis': { name: 'Industry Analysis', enabled: true, priority: 2 },
  'global-literacy': { name: 'Global Literacy', enabled: true, priority: 2 },
  'author-spotlights': { name: 'Author Spotlights', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
};

export const BOOKS_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: false,
  spaceports: false,
  minerals: false,
  fires: false,
  ucdpEvents: false,
  displacement: false,
  climate: false,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  publisherHQs: true,
  bookFairs: true,
  libraries: true,
  literaryLandmarks: true,
  literaryToday: true,
  openLibraryLive: true,
  dayNight: true,
};

export const BOOKS_MOBILE_MAP_LAYERS: MapLayers = {
  ...BOOKS_MAP_LAYERS,
  publisherHQs: false,
  literaryLandmarks: false,
};
